try background-server-action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -150,23 +150,20 @@ jobs:
         $HOME/minio-binaries/mc alias set local http://127.0.0.1:9000 minioadmin minioadmin
         $HOME/minio-binaries/mc mb local/test-data
         $HOME/minio-binaries/mc cp test_data/blogs.parquet local/test-data
-    - name: Start roapi
+    - name: Start roapi and Query
       env:
         AWS_DEFAULT_REGION: "us-east-1"
         AWS_ACCESS_KEY_ID: minioadmin
         AWS_SECRET_ACCESS_KEY: minioadmin
         AWS_ENDPOINT_URL: http://127.0.0.1:9000
-      # run in background, else it blocks next step
-      run: cargo run --bin roapi -- -c test_s3.yml &
-    - name: Wait for roapi available
-      uses: ifaxity/wait-on-action@v1
+      uses: BerniWittmann/background-server-action@v1.0.4
       with:
-        resource: tcp://127.0.0.1:8000
-        # Maximum time in ms to wait before exiting with failure (1) code, default Infinity
-        # 10 minutes = 600,000 ms
-        timeout: 600000
-    - name: Query roapi, Expect 200 response code
-      run: if [ $(curl -o /dev/null -s -w "%{http_code}" -X POST -d 'SELECT count(1) from blogs' 127.0.0.1:8000/api/sql) != "200" ]; then exit 1; fi
+        command: if [ $(curl -o /dev/null -s -w "%{http_code}" -X POST -d 'SELECT count(1) from blogs' 127.0.0.1:8000/api/sql) != "200" ]; then exit 1; fi
+        start: cargo run --bin roapi -- -c test_s3.yml
+        wait-on: "tcp://127.0.0.1:8000"
+        # By default, wait-on will retry for 60 seconds. You can pass a custom timeout in seconds using wait-on-timeout.
+        # 10 minutes = 600 seconds
+        wait-on-timeout: 600
 
   # make sure native-tls always builds
   openssl_build:
